### Docker Compose example
volumes:
  # Portainer
  pt_portainer_data:
    driver: local

services:
  ct_portainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: agorastismesaio/docker-img-portainer:main
    hostname: portainer
    container_name: ct_portainer
    restart: always
    # Change default admin's password to something else, i.e.:
    # htpasswd -nb -B admin super_password | cut -d ":" -f 2 | sed 's/\$/\$\$/g'
    # NOTE, in this case I have to change $ to $$
    command: --admin-password '$$2y$$05$$HgNWTX7t1JUiVLjght9Hv.kRkhlzKLU55a3SNAxMJe42P07BodATi'
    ports:
      - "9000:9000"
    volumes:
      # Access to docker's internals
      - /var/run/docker.sock:/var/run/docker.sock
      - pt_portainer_data:/data
