### Docker Compose example
volumes:
  # Portainer
  pt_portainer_data:
    driver: local

services:
  ct_portainer:
    image: agorastismesaio/docker-img-portainer:main
    hostname: portainer
    container_name: ct_portainer
    restart: always
    # Change default admin's password to something else, i.e.:
    # htpasswd -nb -B admin super_palabra_clave | cut -d ":" -f 2 | sed 's/\$/\$\$/g'
    # NOTE, in this case I have to change $ to $$
    command: --admin-password '$$2y$$05$$DF7OIaxXKLLldraRR.bhs.Tk5wSFr/l4JtW7RuaIGoMAfGB7Al0Qm'
    ports:
      - "9000:9000"
      #- "9443:9443" # For https
    volumes:
      # Access to docker's internals
      - /var/run/docker.sock:/var/run/docker.sock
      - pt_portainer_data:/data
